version: "3"

services:
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=booksdb
      - POSTGRES_PASSWORD=bookspw
      - POSTGRES_USER=booksuser

volumes:
  pgdata: